# /boot/loader.conf.d/bhyve-virtual-machine-host.conf: configuration for FreeBSD boot loader for bhyve virtual machine hosts

# Virtual machine support
if_bridge_load="YES"
if_tap_load="YES"
nmdm_load="YES"
vmm_load="YES"

