# /boot/loader.conf.d/mass-storage-kernel-modules.conf: configuration for FreeBSD boot loader to load kernel modules for mass storage devices

# Broadcom 9500-16i HBA support
# The `mpr` kernel module doesn’t get automatically loaded when this HBA is
# connected.
mpr_load="YES"

