# /etc/periodic.conf.d/hourly-periodic-jobs.conf

# These options are used by periodic(8) itself to determine what to do
# with the output of the sub-programs that are run, and where to send
# that output. $hourly_output might be set to /var/log/hourly.log if you
# wish to log the hourly output and have the files rotated by newsyslog(8)
#
hourly_output="root"                                    # user or /file
hourly_show_success="YES"                               # scripts returning 0
hourly_show_info="YES"                                  # scripts returning 1
hourly_show_badconfig="NO"                              # scripts returning 2

