# /etc/periodic.conf: periodic system configuration

#----------------------------------------------------------
# Support for modular periodic scripts configuration
#----------------------------------------------------------

for _periodic_conf_file in ${periodic_conf_files}
do
    case ${_periodic_conf_file} in
        */periodic.conf)
            _periodic_discrete_conf_directory="${_periodic_conf_file}.d"
            if [ -d "${_periodic_discrete_conf_directory}" ]
            then
                for _periodic_discrete_conf_file in "${_periodic_discrete_conf_directory}"/*.conf
                do
                    if [ -f "${_periodic_discrete_conf_file}" ] && [ -r "${_periodic_discrete_conf_file}" ]
                    then
                        . "${_periodic_discrete_conf_file}"
                    fi
                done
            fi
            ;;
        *)
            # Skip other periodic configuration files, such as
            # /etc/periodic.conf.local, which is in the same directory as
            # /etc/periodic.conf.
            ;;
    esac
done

