# /etc/pf.conf: Configuration for Packet Filter

#-----------------------------------------------------------
# Variables
#-----------------------------------------------------------

ext_if = "vtnet0"
tcp_services = "{ ssh, domain, http, https, smtp, smtps, submission }"
udp_services = "{ domain }"
icmp_types = "{ echoreq, unreach }"

# NFS auxiliary ports.
nfs_mountd_port = "2050"
nfs_lockd_port = "2051"
nfs_statd_port = "2052"

# Ports that need to be open for both TCP and UDP in the LAN subnet.
tcp_and_udp_services_for_lan_subnet = "{ sunrpc, nfsd, " $nfs_mountd_port ", " $nfs_lockd_port ", " $nfs_statd_port " }"

lan_subnet = "{10.0.0.0/16}"

cloud_servers = "{123.231.123.231, 231.123.231.123}"


#-----------------------------------------------------------
# Tables
#-----------------------------------------------------------

# Define persistent table of abusive hosts.
table <abusive_hosts> persist

# Define persistent table for hosts banned by sshguard.
table <sshguard> persist


#-----------------------------------------------------------
# Options
#-----------------------------------------------------------

# Ignore loopback interface.
set skip on lo0

# Protect against activity from spoofed or forged IP addresses.
antispoof quick for $ext_if


#-----------------------------------------------------------
# Rules
#-----------------------------------------------------------

# Allow all outgoing traffic.
pass out quick

# Allow all incoming traffic from local area network for allowed TCP services.
pass in quick on $ext_if proto tcp from $lan_subnet to any port $tcp_services

# Allow all incoming traffic from local area network for allowed local TCP
# and UDP services.
pass in quick on $ext_if proto { tcp, udp } from $lan_subnet to any port $tcp_and_udp_services_for_lan_subnet

# Allow all incoming traffic from personal cloud servers for allowed TCP
# services.
pass in quick on $ext_if proto tcp from $cloud_servers to any port $tcp_services

# Block all incoming traffic from abusive hosts table.
block in quick from <abusive_hosts>

# Block all incoming traffic from sshguard table.
block in quick from <sshguard>

# Block all incoming traffic…
block in

# …except for allowed TCP services with rate limiting against abusive hosts…
pass in quick on $ext_if proto tcp to any port $tcp_services    \
    flags S/SA keep state                                       \
    (max-src-conn 100, max-src-conn-rate 15/5,                  \
    overload <abusive_hosts> flush)

# …and UDP services, as well as ICMP.
pass in quick on $ext_if proto udp to any port $udp_services
pass in quick on $ext_if inet proto icmp all icmp-type $icmp_types

