#! /bin/sh

cd /etc/pam.d
for file_name in su-password-prompt-pam-system.diff ssh-password-prompt-pam-sshd.diff
do
    patch --posix -p1 -i /homelab-documentation/freebsd-server/password-prompts/patches/${file_name}
done

