# /usr/local/etc/nginx/sites-enabled/my_domain.tld.conf

server {
    listen       80;
    listen       [::]:80;
    server_name  my_domain.tld www.my_domain.tld;
    include redirect_to_ssl;
}

server {
    listen       443 ssl;
    listen       [::]:443 ssl;
    http2        on;
    server_name  my_domain.tld www.my_domain.tld;

    include ssl_wildcard_certificate;

    root /usr/local/www/my_domain.tld;
    include error_pages;
    include php;

    client_max_body_size 50m;
}
