# /usr/local/etc/periodic.conf.d/smart-status.conf: daily SMART status reports

# Automatically derive the list of drives to monitor based on the ones
# listed in /usr/local/etc/smartd.conf.

if [ -f /usr/local/etc/smartd.conf ] && [ -r /usr/local/etc/smartd.conf ]
then
    daily_status_smart_devices=$(/usr/bin/grep -o "^/dev/[a-z0-9]*" /usr/local/etc/smartd.conf)
    daily_status_smart_devices=$(/bin/echo "${daily_status_smart_devices}" | /usr/bin/sort)
    daily_status_smart_devices=$(/bin/echo "${daily_status_smart_devices}" | /usr/bin/tr '\n' ' ')
    daily_status_smart_devices=$(/bin/echo "${daily_status_smart_devices}" | /usr/bin/sed "s,[[:space:]]*$,,")
fi

